# Generated by Django 6.0.5 on 2026-05-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAGenerationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('best_fitness', models.FloatField()),
                ('avg_fitness', models.FloatField()),
                ('gini_coefficient', models.FloatField()),
                ('coverage_rate', models.FloatField()),
                ('priority_satisfaction_rate', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='optimization.allocationrun')),
            ],
            options={
                'ordering': ['run', 'generation'],
            },
        ),
    ]
