# Generated by Django 6.0.5 on 2026-05-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ic_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('district', models.CharField(choices=[('george_town', 'George Town'), ('bayan_lepas', 'Bayan Lepas'), ('butterworth', 'Butterworth'), ('seberang_perai', 'Seberang Perai'), ('balik_pulau', 'Balik Pulau'), ('air_itam', 'Air Itam'), ('jelutong', 'Jelutong'), ('tanjung_bungah', 'Tanjung Bungah')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('monthly_income', models.FloatField()),
                ('income_category', models.CharField(choices=[('extreme_poor', 'Extreme Poor (< RM1,000)'), ('poor', 'Poor (RM1,000 - RM2,000)'), ('vulnerable', 'Vulnerable (RM2,001 - RM4,850)')], max_length=20)),
                ('household_size', models.PositiveIntegerField()),
                ('has_oku', models.BooleanField(default=False)),
                ('has_elderly', models.BooleanField(default=False)),
                ('has_infant', models.BooleanField(default=False)),
                ('priority_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
    ]
