# Generated by Django 6.0.5 on 2026-05-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='employment_status',
            field=models.CharField(choices=[('unemployed', 'Unemployed'), ('informal_sector', 'Informal Sector (odd jobs, hawker, daily wage)'), ('employed', 'Employed (formal/permanent)')], default='employed', max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='is_single_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
