# Generated by Django 6.0.5 on 2026-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_employment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='employment_status',
            field=models.CharField(choices=[('unemployed', 'Unemployed'), ('informal_sector', 'Informal Sector (odd jobs, hawker, daily wage)'), ('employed', 'Employed (formal/permanent)')], db_default='employed', default='employed', max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='is_single_parent',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='num_children',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
