# Generated by Django 6.0.5 on 2026-05-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_generations', models.PositiveIntegerField(default=100)),
                ('population_size', models.PositiveIntegerField(default=50)),
                ('crossover_rate', models.FloatField(default=0.8)),
                ('mutation_rate', models.FloatField(default=0.1)),
                ('elitism_count', models.PositiveIntegerField(default=2)),
                ('total_food_packages', models.PositiveIntegerField(default=100)),
                ('max_per_household', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('best_fitness', models.FloatField(blank=True, null=True)),
                ('gini_coefficient', models.FloatField(blank=True, null=True)),
                ('coverage_rate', models.FloatField(blank=True, null=True)),
                ('priority_satisfaction_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.PositiveIntegerField(default=0)),
                ('is_served', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='optimization.allocationrun')),
            ],
            options={
                'ordering': ['-beneficiary__priority_score'],
            },
        ),
    ]
