# Generated by Django 6.0.5 on 2026-05-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_weight', models.FloatField(default=40.0)),
                ('household_size_weight', models.FloatField(default=25.0)),
                ('oku_weight', models.FloatField(default=20.0)),
                ('elderly_weight', models.FloatField(default=10.0)),
                ('infant_weight', models.FloatField(default=5.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Priority Criteria',
            },
        ),
    ]
