# Generated by Django 6.0.5 on 2026-05-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritycriteria',
            name='children_weight',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='prioritycriteria',
            name='employment_weight',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='prioritycriteria',
            name='single_parent_weight',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='prioritycriteria',
            name='elderly_weight',
            field=models.FloatField(default=8.0),
        ),
        migrations.AlterField(
            model_name='prioritycriteria',
            name='household_size_weight',
            field=models.FloatField(default=13.0),
        ),
        migrations.AlterField(
            model_name='prioritycriteria',
            name='income_weight',
            field=models.FloatField(default=33.0),
        ),
        migrations.AlterField(
            model_name='prioritycriteria',
            name='infant_weight',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='prioritycriteria',
            name='oku_weight',
            field=models.FloatField(default=14.0),
        ),
    ]
